import { USER_GROUPS, type UserGroup } from '@/types/login/auth.types';

export const TRANSACTION_PERMISSIONS = {
  REFUND_TRANSACTION: 'REFUND_TRANSACTION',
  CAPTURE_TRANSACTION: 'CAPTURE_TRANSACTION',
  VOID_TRANSACTION: 'VOID_TRANSACTION',
  DISPUTE_TRANSACTION_ACCESS: 'DISPUTE_TRANSACTION_ACCESS',
  EDIT_STATUS_BUTTON: 'EDIT_STATUS_BUTTON',
} as const;

export type TransactionPermission =
  (typeof TRANSACTION_PERMISSIONS)[keyof typeof TRANSACTION_PERMISSIONS];

const PERMISSION_GROUPS: Record<TransactionPermission, UserGroup[]> = {
  REFUND_TRANSACTION: [
    USER_GROUPS.OPERATIONS,
    USER_GROUPS.SUPPORT,
    USER_GROUPS.FINANCE,
    USER_GROUPS.SYSADMIN,
  ],
  CAPTURE_TRANSACTION: [USER_GROUPS.OPERATIONS, USER_GROUPS.SUPPORT, USER_GROUPS.SYSADMIN],
  VOID_TRANSACTION: [USER_GROUPS.OPERATIONS, USER_GROUPS.SUPPORT, USER_GROUPS.SYSADMIN],
  DISPUTE_TRANSACTION_ACCESS: [
    USER_GROUPS.FRAUD,
    USER_GROUPS.RISK,
    USER_GROUPS.RISK_COMPLIANCE,
    USER_GROUPS.OPERATIONS,
    USER_GROUPS.SUPPORT,
    USER_GROUPS.SYSADMIN,
  ],
  EDIT_STATUS_BUTTON: [USER_GROUPS.OPERATIONS, USER_GROUPS.SYSADMIN],
};

export function hasAccess(permission: TransactionPermission, userGroups: string[]): boolean {
  const allowed = PERMISSION_GROUPS[permission];
  return allowed.some((g) => userGroups.includes(g));
}
