import {
  AlertCircle,
  Archive,
  Bell,
  Bookmark,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsUpDown,
  CircleUser,
  CircleX,
  Coins,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Globe,
  Info,
  KeyRound,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Moon,
  Move,
  Pencil,
  Plus,
  ReceiptText,
  Search,
  Share2,
  SlidersHorizontal,
  Sun,
  Table,
  Timer,
  Trash,
  Trash2,
  UserCheck,
  UserCog,
  X,
  XCircle,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

const ICON_MAP = {
  'alert-circle': AlertCircle,
  archive: Archive,
  bell: Bell,
  bookmark: Bookmark,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-down': ChevronsDown,
  'chevrons-up-down': ChevronsUpDown,
  'circle-user': CircleUser,
  'circle-x': CircleX,
  coins: Coins,
  copy: Copy,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  filter: Filter,
  globe: Globe,
  info: Info,
  'key-round': KeyRound,
  'loader-2': Loader2,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  moon: Moon,
  move: Move,
  pencil: Pencil,
  plus: Plus,
  'receipt-text': ReceiptText,
  search: Search,
  'share-2': Share2,
  'sliders-horizontal': SlidersHorizontal,
  sun: Sun,
  table: Table,
  timer: Timer,
  trash: Trash,
  'trash-2': Trash2,
  'user-check': UserCheck,
  'user-cog': UserCog,
  x: X,
  'x-circle': XCircle,
} as const satisfies Record<string, LucideIcon>;

export type DasIconName = keyof typeof ICON_MAP;

interface DasIconProps extends LucideProps {
  name: DasIconName;
}

export function DasIcon({ name, ...props }: DasIconProps) {
  const Icon = ICON_MAP[name];
  return <Icon {...props} />;
}
